version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - /opt/pgsql/data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 192.168.101.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - /opt/pgadmin/data:/var/lib/pgadmin
    networks:
      app_net:
        ipv4_address: 192.168.101.3

networks:
  app_net: 
    ipam:
      driver: default
      config:
        - subnet: "192.168.101.0/24"
          gateway: 192.168.101.1

      